class User < ApplicationRecord
  # extends ...................................................................

  # includes ..................................................................
  include TagColumns

  # relationships .............................................................

  # validations ...............................................................
  validates :email, presence: true, uniqueness: true

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable
  tag_columns :roles

  # class methods .............................................................
  class << self
  end

  # public instance methods ...................................................

  def admin?
    has_role?(:admin)
  end

  # protected instance methods ................................................
  protected

  # private instance methods ..................................................
  private
end
